<?php
$aaacceptImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqAccept.gif\" title=\"Update row\" alt=\"Accept\">";
$acceptImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqAccept.gif\" title=\"Update record\" alt=\"Accept\">";
$acceptImageMed= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqAccept.gif\" title=\"Update record\" alt=\"Accept\">";
$addEventImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}newEvent.gif\" title=\"Click here to create a new event\" alt=\"Add Event\">";
$addEventImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}newEventSml.gif\" title=\"Click here to create a related event\" alt=\"Add Related Event\">";
$addImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgNew.gif\" title=\"Click here to create a new record\" alt=\"New Record\">";
$addImageMed= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqClear.gif\" title=\"Click here to create a new record\" alt=\"New Record\">";
$addImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smNew.gif\" title=\"Click here to create a new record\" alt=\"New Record\">";
$addLaborTransaction= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smNew.gif\" title=\"Click here to add a labor transaction\" alt=\"Add Labor Transaction\">";
$addMoreImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqAdd.gif\" title=\"Click here to add more lines\" alt=\"Add\">";
$addOrderImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgOrder.gif\" title=\"Click here to create a new order\" alt=\"Order\">";
$addOrderImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smOrder.gif\" title=\"Click here to create a new order\" alt=\"Order\">";
$addScheduleException= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}newEventSml.gif\" title=\"Click here to add a schedule exception\" alt=\"Add Schedule Exception\">";
$addShiftTransaction= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smNew.gif\" title=\"Click here to add a shift transaction\" alt=\"Add Shift Transaction\">";
$addToImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqAccept.gif\" title=\"Click here to add to current search criteria\" alt=\"Add\">";
$altProdStrImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}altProdStructure.gif\" title=\"Click here to view the alternate single level explosion\" alt=\"Alternate Single Level Explosion\">";
$altPsmImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smOpenBox.gif\" title=\"Display alternate product structure\" alt=\"Alternate Product Structure\">";
$altRefRtgImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}prodStructure.gif\" title=\"View the alternate reference routing\" alt=\"Alternate Reference Routing\">";
$altRtgImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smHere.gif\" title=\"Display alternate routings\" alt=\"Alternate Routings\">";
$applCashAcceptImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqAccept.gif\" title=\"Click here to accept the payment\" alt=\"Accept\">";
$applCashAddPaymentLine= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smExpand.gif\" title=\"Click to add a payment line\" alt=\"Add Line\">";
$applCashDefaultInfoImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqGetSettings.gif\" title=\"Click here to default information\" alt=\"Default\">";
$applCashDocAddImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqAdd.gif\" title=\"Click here to add or select a document\" alt=\"Document\">";
$applCashQuickAddImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqAdd.gif\" title=\"Click here to add payment\" alt=\"Add\">";
$applCashQuickChgImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqAdd.gif\" title=\"Click here to update payment\" alt=\"Update\">";
$applCashValidateImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqAccept.gif\" title=\"Click here to release resources and return\" alt=\"Validate\">";
$applyVarianceImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqAdd.gif\" title=\"Click here to add variance amount to payment\" alt=\"Update\">";
$approvedImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}approved.gif\" title=\"Approved\" alt=\"Approved\">";
$arCashPmtImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}costCat.gif\" title=\"Enter Payment\" alt=\"Payment\">";
$arPayerPaymentCancelImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqCancel.gif\" title=\"Click here to clear the List\" alt=\"Clear List\">";
$arPayerPaymentListImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgProcessGo.gif\" title=\"Click here to process List\" alt=\"List\">";
$attachImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgAttachment.gif\" title=\"Click here to view attachments\" alt=\"Attachments\">";
$attachImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smAttachment.gif\" title=\"Click here to view attachments\" alt=\"Attachments\">";
$authorizedImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}selected.gif\" title=\"{$authorizedTitle}\" alt=\"Authorized\">";
$availableImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}available.gif\" title=\"Available For Update\" alt=\"Available For Update\">";
$barChartHide= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}barChartHide.png\" title=\"Hide Bar Chart\" alt=\"Hide Chart\">";
$barChartView= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}barChartView.png\" title=\"View Bar Chart\" alt=\"View Chart\">";
$benefitInfoImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}question.gif\" title=\"Benefit Information\" alt=\"Benefit Info\">";
$botOfFormImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqDown.gif\" title=\"Bottom Of Form\" alt=\"Bottom\">";
$buildImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smConfigure.gif\" title=\"Click here to import to Map Interface table\" alt=\"Map\">";
$calendarImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smCalendar.gif\" title=\"Display calendar\" alt=\"Calendar\">";
$calendarImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgCalendar.gif\" title=\"Display Calendar\" alt=\"Calendar\">";
$calSelWeekImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smPointRightRed.gif\" title=\"View Week\" alt=\"View Week\">";
$cancelImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqNoChange.gif\" title=\"Cancel record update\" alt=\"Cancel\">";
$cancelImageMed= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqNoChange.gif\" title=\"Cancel record update\" alt=\"Cancel\">";
$cfgHdrTransImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}selected.gif\" title=\"Click here to transfer\" alt=\"Transfer\">";
$cfgItemImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smConfigure.gif\" title=\"Click here to view features/options\" alt=\"Configure\">";
$changeAllImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgUpdateAll.gif\" title=\"Update all rows\" alt=\"Update All\">";
$changeImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgUpdate.gif\" title=\"Update record\" alt=\"Update\">";
$changeImageMed= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqUpdate.gif\" title=\"Update record\" alt=\"Update\">";
$changeImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smUpdate.gif\" title=\"Update record\" alt=\"Update\">";
$checkImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}wfActivity.gif\" title=\"{$checkImageTitle}\" alt=\"Check\">";
$chgImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smUpdate.gif\" title=\"{$chgImageSmlTitle}\" alt=\"Update\">";
$chgQtyImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqQuantity.gif\" title=\"Change quantity\" alt=\"Change Quantity\">";
$clearFormFields= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqUpdate.gif\" title=\"Clear form fields\" alt=\"Clear\">";
$clockImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgClock.gif\" title=\"Change Time\" alt=\"Clock\">";
$closeClearImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smClose.gif\" title=\"Close and Clear\" alt=\"Close and Clear\">";
$closeImageMed= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqNoChange.gif\" title=\"Close\" alt=\"Close\">";
$closeSelImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smClose.gif\" title=\"Close\" alt=\"Close\">";
$closeWinImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqClose.gif\" title=\"Close Window\" alt=\"Close\">";
$closeWinImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smClose.gif\" title=\"Close Window\" alt=\"Close\">";
$commentAcceptImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqAccept.gif\" title=\"Click here to accept entry\" alt=\"Accept\">";
$commentClearImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqClear.gif\" title=\"Click here to clear entry\" alt=\"Clear\">";
$commentDftImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqFolder.gif\" title=\"Click here to default entry\" alt=\"Default\">";
$commentExistImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smComment.gif\" title=\"View/Add/Edit comments\" alt=\"Comments\">";
$commentExistImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgComment.gif\" title=\"View/Add/Edit comments\" alt=\"Comments\">";
$commentExistImageNoTitle= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smComment.gif\" alt=\"Comments\">";
$commentHdrImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgCommentHdr.gif\" title=\"Header comments\" alt=\"Header Comments\">";
$commentImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smCommentNone.gif\" title=\"Add comments\" alt=\"Comments\">";
$commentResetImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqRefresh.gif\" title=\"Click here to reset entry\" alt=\"Reset\">";
$commentRetrieveImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smComment.gif\" title=\"Retrieve comments\" alt=\"Comments\">";
$commentTrlImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgCommentTrl.gif\" title=\"Trailer comments\" alt=\"Trailer Comments\">";
$commentView= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smComment.gif\" title=\"Display comments\" alt=\"Comments\">";
$compDispImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}compDisp.gif\" title=\"Inventory Use-Up Item\" alt=\"CD\">";
$compMatlImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smOpenBox.gif\" title=\"Display component material\" alt=\"Component Material\">";
$copyAllImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgCopy.gif\" title=\"Copy all records\" alt=\"Copy All\">";
$copyAllImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smCopy.gif\" title=\"Copy all\" alt=\"Copy All\">";
$copyBiLevelImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgCopy.gif\" title=\"Bi-Level Copy\" alt=\"Bi-Level Copy\">";
$copyImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgCopy.gif\" title=\"Copy record\" alt=\"Copy\">";
$copyImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smCopy.gif\" title=\"Copy record\" alt=\"Copy\">";
$copyStdImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgCopy.gif\" title=\"Copy all from standard\" alt=\"Copy All from Standard\">";
$costCategorySml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}costCat.gif\" title=\"Display Cost Category Records\" alt=\"Cost Category\">";
$createPO= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smP.gif\" title=\"Click here to add item to a Purchase Order\" alt=\"PO\">";
$dashboard= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}dashboard.png\" title=\"View Dashboard\" alt=\"Dashboard\">";
$deactivateSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smCloseLine.gif\" title=\"Deactivate Employee HR\" alt=\"Deactivate Employee HR\">";
$deductions= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smD.gif\" title=\"Click here to maintain deductions\" alt=\"D\">";
$deleteAllImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgDelete.gif\" title=\"Remove all records\" alt=\"Remove All\">";
$deleteBiLevelImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgDelete.gif\" title=\"Bi-Level Delete\" alt=\"Bi-Level Delete\">";
$deleteFixLibImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smCloseLine.gif\" title=\"Delete Fix Library\" alt=\"Delete\">";
$deleteImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgDelete.gif\" title=\"Remove record\" alt=\"Remove\">";
$deleteImageMed= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqDelete.gif\" title=\"Remove record\" alt=\"Remove\">";
$deleteImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smDelete.gif\" title=\"Remove record\" alt=\"Remove\">";
$dependentsImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}dependents.gif\" title=\"Spouse And Dependents\" alt=\"Dependents\">";
$deselectAllImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqNoCheck.gif\" title=\"Click here to deselect all\" alt=\"Deselect All\">";
$displaySpoolFile= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqFolder.gif\" title=\"Display Spool File\" alt=\"Display\">";
$downloadCsv= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}downloadCsv.png\" title=\"Download CSV\" alt=\"CSV\">";
$downloadProblemFiles= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqRefresh.gif\" title=\"Download Problem Files\" alt=\"Download Problem Files\">";
$drillDownCmtImg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smComment.gif\" title=\"Display comments\" alt=\"Comments\">";
$drillDownRowImg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smExpand.gif\" title=\"Show info about this Row\" alt=\"Display\">";
$earnnotavailImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}earningsnotavailable.gif\" title=\"Not Available\" alt=\"Not Available\">";
$editBaseReadmeImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgUpdate.gif\" title=\"Edit Base Readme\" alt=\"Base Readme\">";
$editNoUpdateSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}newEventSml.gif\" title=\"Click here to edit without update\" alt=\"Edit\">";
$emailImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgEmail.gif\" title=\"E-mail/Fax\" alt=\"E-mail\">";
$emailSpoolFile= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smEmail.gif\" title=\"E-mail Spool File\" alt=\"E-mail\">";
$emplMaintImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}applicants2.gif\" title=\"Employee Maintenance\" alt=\"Employee Maintenance\">";
$enrollmentImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}enrollment.gif\" title=\"Benefit Enrollment\" alt=\"Benefit Enrollment\">";
$entryAcceptImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqAccept.gif\" title=\"Click here to accept entry\" alt=\"Accept\">";
$featRtgImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}referenceRouting.gif\" title=\"View the feature routing\" alt=\"Feature Routing\">";
$featuresImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}features.gif\" title=\"Click here to display features\" alt=\"Features\">";
$finalizeImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}approved.gif\" title=\"Finalize Problem\" alt=\"Finalize\">";
$fixPrepImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}selected.gif\" title=\"Click here to run Fix Prep\" alt=\"Fix Prep\">";
$forecastImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smF.gif\" title=\"Consolidated Forecast\" alt=\"Forecast\">";
$formatPrintDesc= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgprint.gif\" title=\"Click here for printer friendly version\" alt=\"Printable Version\">";
$formatPrintMed= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqPrint.gif\" title=\"Click here for printer friendly version\" alt=\"Printable Version\">";
$form301= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}form301.gif\" title=\"Form 301\" alt=\"Form301\">";
$foundImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smCamera.gif\" title=\"View picture\" alt=\"Picture\">";
$generateProgrammerTestlImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgCommentTrl.gif\" title=\"Generate Programmer Test\" alt=\"Generate Programmer Test\">";
$goSearchImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqFind.gif\" title=\"Click here to search\" alt=\"Go\">";
$goSearchImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgFind.gif\" title=\"Click here to search\" alt=\"Go\">";
$helpBookImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}imgHelpLibrary.gif\" title=\"Click here to view system documentation\" alt=\"Documentation\">";
$helpPageImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgHelp.gif\" title=\"Click here for help on this page\" alt=\"Help\">";
$helpPageImageMed= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqQuestion.gif\" title=\"Click here for help on this page\" alt=\"Help\">";
$inactiveImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smX.gif\" title=\"Inactive record\" alt=\"Inactive\">";
$indentedStkStsImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}indentedStockStatus.gif\" title=\"View the indented stock status\" alt=\"Indented Stock Status\">";
$inquiryChgSelLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgUpdate.gif\" title=\"Click here to update inquiry options\" alt=\"Update\">";
$kanbanRetireImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}rejected.gif\" title=\"Retire\" alt=\"Retire\">";
$kanbanSetupImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smConfigure.gif\" title=\"Review Setup\" alt=\"Setup\">";
$kitOptionImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smKitOption.gif\" title=\"Click here for kit options\" alt=\"Kit\">";
$kitOptionImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgKitOption.gif\" title=\"Kit Quickview\" alt=\"Kit\">";
$laborIPImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smHere.gif\" title=\"Display labor in process\" alt=\"Labor In Process\">";
$lgC= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgC.gif\" title=\"{$lgCTitle}\" alt=\"C\">";
$lgH= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgH.gif\" title=\"{$lgHTitle}\" alt=\"H\">";
$lgO= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgO.gif\" title=\"{$lgOTitle}\" alt=\"O\">";
$lgT= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgT.gif\" title=\"{$lgTTitle}\" alt=\"T\">";
$lgU= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgU.gif\" title=\"{$lgUTitle}\" alt=\"U\">";
$lineCloseImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqNoChange.gif\" title=\"Click here to close this line\" alt=\"Close\">";
$lineOpenImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqOpen.gif\" title=\"Click here to reopen this line\" alt=\"Reopen\">";
$loadACAEligibility= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}newEvent.gif\" title=\"Click here to load ACA Employee Eligibility\" alt=\"Load Eligibility\">";
$lotIndentExpImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smCommentNone.gif\" title=\"View the lot indented explosion\" alt=\"Indented Explosion\">";
$lotIndentWUImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smCommentNone.gif\" title=\"View the lot indented where used\" alt=\"Indented Where Used\">";
$lunchsml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smL.gif\" title=\"Lunch Maintenance\" alt=\"Lunch Maint\">";
$mapColumnImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}mapColumn.gif\" title=\"Display columns\" alt=\"Column\">";
$mbLogo= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}mbLogo.gif\" title=\"Logo\" alt=\"Logo\">";
$mbOrderAccept= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}mbSqAccept.gif\" title=\"Click here to accept the order\" alt=\"Accept\">";
$mbOrderAdd= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}mbSqAdd.gif\" title=\"Click here to add item to the order\" alt=\"Add\">";
$mbOrderBack= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}mbSqBack.gif\" title=\"Previous page\" alt=\"Back\">";
$mbOrderCancel= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}mbSqCancel.gif\" title=\"Click here to cancel order\" alt=\"Cancel\">";
$mbOrderChg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}mbSqAccept.gif\" title=\"Click here to update the order\" alt=\"Change\">";
$mbOrderContinue= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}mbSqContinue.gif\" title=\"Click here to continue\" alt=\"Continue\">";
$mbOrderReview= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}mbSqCart.gif\" title=\"Click here to view order detail\" alt=\"View\">";
$moreInfoImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqInfo.gif\" title=\"More information\" alt=\"More\">";
$moveImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgCopy.gif\" title=\"Move record\" alt=\"Move\">";
$moveImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smCopy.gif\" title=\"Move record\" alt=\"Move\">";
$nextImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqRight.gif\" title=\"Next page\" alt=\"Next\">";
$nextImageEndSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smRightEnd.gif\" title=\"{$nextImageEndTitle}\" alt=\"Next\">";
$nextImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smRight.gif\" title=\"{$nextImageTitle}\" alt=\"Next\">";
$nextPrevBlank= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqBlank.gif\">";
$nonStockImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqN.gif\" title=\"Click here to add a non-stock item\" alt=\"NonStock\">";
$notavailableImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}notavailable.gif\" title=\"Not Available\" alt=\"Not Available\">";
$notselectedImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}notselected.gif\" title=\"Not Selected\" alt=\"Not Selected\">";
$optionsHideImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqRemove.gif\" title=\"Click here to hide options\" alt=\"Hide\">";
$optionsImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}options.gif\" title=\"Click here to display options\" alt=\"Options\">";
$optionsViewImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqAdd.gif\" title=\"Click here to view options\" alt=\"Options\">";
$orderAcceptImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqAccept.gif\" title=\"Click here to accept the order\" alt=\"Accept\">";
$orderAddToImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqCart.gif\" title=\"Click here to add selected items to the order\" alt=\"Add\">";
$orderCancelImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqCancel.gif\" title=\"Click here to cancel the order\" alt=\"Cancel Order\">";
$orderCloseImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgDelete.gif\" title=\"Close/Cancel Order\" alt=\"Close/Cancel Order\">";
$orderContinueImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqContinue.gif\" title=\"Click here to continue the order process\" alt=\"Continue\">";
$orderCreditCardImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgCC.gif\" title=\"Click here to pay by credit card\" alt=\"Credit Card\">";
$orderDftQtyImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smPointRightRed.gif\" title=\"Click here to default last order quantity to order quantity\" alt=\"Default Qty\">";
$orderFlagsImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smF.gif\" title=\"Click here to view Order Flags\" alt=\"Flags\">";
$orderNoBlanketImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqRemove.gif\" title=\"Click here to remove blanket line\" alt=\"Remove\">";
$orderNoUpdateImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqCancel.gif\" title=\"Click here to NOT update the order\" alt=\"No Update\">";
$orderUpdateImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqAdd.gif\" title=\"Click here to update the order\" alt=\"Update\">";
$orderUpdPriceImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqRecalc.gif\" title=\"Click here to update the price\" alt=\"Update Price\">";
$orderViewDtlImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqBinoculars.gif\" title=\"Click here to view order detail\" alt=\"View Detail\">";
$pageIDImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smPage.gif\" title=\"Display a list of pages for this table\" alt=\"Pages\">";
$pageSelect= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgPageLayout.gif\" title=\"Click here to change the page layout\" alt=\"Page\">";
$payerCustomerImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}mapColumn.gif\" title=\"Display Customers of Payer\" alt=\"Customer\">";
$paySubCodeImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}mapColumn.gif\" title=\"Display Payment Sub Code\" alt=\"Sub Code\">";
$pendingImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}foryourapproval.gif\" title=\"Pending Approval\" alt=\"Pending\">";
$planDocImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}plandocument.gif\" title=\"Provider Information\" alt=\"Provider Information\">";
$pltImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smPlant.gif\" title=\"Display Plant Records\" alt=\"Plant\">";
$portalHome= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgHome.gif\" title=\"Return to main page\" alt=\"Main\">";
$portalHomeMed= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqHome.gif\" title=\"Return to main page\" alt=\"Main\">";
$previousImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqLeft.gif\" title=\"Previous page\" alt=\"Previous\">";
$previousImageBegSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smLeftBeg.gif\" title=\"{$previousImageBegTitle}\" alt=\"Previous\">";
$previousImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smLeft.gif\" title=\"{$previousImageTitle}\" alt=\"Previous\">";
$printMO= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqPrint.gif\" title=\"Click here to print Mfg Order\" alt=\"Print Mfg Order\">";
$probIDObsolete= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smClose.gif\" title=\"Obsolete\" alt=\"Obsolete\">";
$probidSel4Recompile= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smR.gif\" title=\"Click here to select for recompile only\" alt=\"R\">";
$probidSourceSel= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}report.gif\" title=\"Source Selection\" alt=\"Source\">";
$probIDUnObsolete= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqRefresh.gif\" title=\"Un-Obsolete\" alt=\"Un-Obsolete\">";
$prodStrImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}altProdStructure.gif\" title=\"Click here to view the single level explosion\" alt=\"Single Level Explosion\">";
$prodStrIndentImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}prodStructure.gif\" title=\"View the indented product structure\" alt=\"Indented Explosion\">";
$publishLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSave.gif\" title=\"Click here to publish\" alt=\"Publish\">";
$publishSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smSave.gif\" title=\"Click here to publish\" alt=\"Publish\">";
$QAPrint= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}dependents.gif\" title=\"Q/A Print\" alt=\"Q/A Print\">";
$qlinkAllLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqRefresh.gif\" title=\"Click here to view all\" alt=\"View All\">";
$qlinkClearLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqStop.gif\" title=\"Click here to hide all\" alt=\"Hide All\">";
$qlinkDftLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqGetSettings.gif\" title=\"Click here to use the default view\" alt=\"Use default\">";
$qlinkDftRowLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqRemove.gif\" title=\"Click here for default number of rows\" alt=\"Default rows\">";
$qlinkMaxRowLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqAdd.gif\" title=\"Click here to display all rows\" alt=\"All rows\">";
$qlinkSetLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqSaveSettings.gif\" title=\"Click here to save the current view as the default\" alt=\"Save current as default\">";
$reactivate= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smR.gif\" title=\"Click here to reactivate this row\" alt=\"R\">";
$recalcTaxesImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqT.gif\" title=\"Click here to recalculate taxes\" alt=\"Recalc\">";
$recheckImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}selected.gif\" title=\"Click here to recheck component availability\" alt=\"Recheck\">";
$refRtgImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}referenceRouting.gif\" title=\"View the reference routing\" alt=\"Reference Routing\">";
$regenOptionsImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqRefresh.gif\" title=\"Click here to regenerate fixed price options\" alt=\"Regenerate\">";
$rejectedImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}rejected.gif\" title=\"Rejected\" alt=\"Rejected\">";
$relatedColumns= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smR.gif\" title=\"Click here to maintain the related columns\" alt=\"R\">";
$releaseBatchImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqRefresh.gif\" title=\"Release Batch\" alt=\"Release\">";
$releaseCustomerImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqRefresh.gif\" title=\"Release Customer\" alt=\"Release\">";
$releaseImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}approved.gif\" title=\"Release To Production\" alt=\"Release\">";
$reloadImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqRefresh.gif\" title=\"Refresh Page\" alt=\"Refresh\">";
$reportBatchImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqPrint.gif\" title=\"Click here to print information\" alt=\"Printable Version\">";
$reportImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqPrint.gif\" title=\"Click here to print information from Interface table\" alt=\"Printable Version\">";
$resetPaps= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smR.gif\" title=\"Click here to reset the paper switch\" alt=\"Reset Paper Switch\">";
$retrieveAvailableSoftwareUpdates= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqRefresh.gif\" title=\"Retrieve Available Software Updates\" alt=\"Retrieve Available Software Updates\">";
$reverseBatchImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smR.gif\" title=\"Click here to reverse payments in the batch\" alt=\"Reverse\">";
$rmvApprovalImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}rejected.gif\" title=\"Remove Approval\" alt=\"Unapprove\">";
$rmvReadyToApproveAllImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqNoCheck.gif\" title=\"Remove Requisition Ready For Approval\" alt=\"Deselect Ready\">";
$salesInqImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgLibrary.gif\" title=\"Display library of Sales Inquiries\" alt=\"Sales Inquiries\">";
$saveImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSave.gif\" title=\"Save Record\" alt=\"Save\">";
$saveImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smSave.gif\" title=\"Save Record\" alt=\"Save\">";
$sbmSchdImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgProcessGo.gif\" title=\"Click here to process selection\" alt=\"Process\">";
$sbmSchdImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smProcessGo.gif\" title=\"Click here to process selection\" alt=\"Process\">";
$sbmSchdParmImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgClock.gif\" title=\"Click here for schedule options\" alt=\"Schedule\">";
$sbmSchdResetImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgErase.gif\" title=\"Click here to reset selection criteria\" alt=\"Reset\">";
$sbmSchdRtvImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgOpen.gif\" title=\"Click here to retrieve a selection\" alt=\"Retrieve Selection\">";
$sbmSchdSaveImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSave.gif\" title=\"Click here to save current selection\" alt=\"Save Selection\">";
$searchDesc= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSearch.gif\" title=\"Click here for Advanced Search\" alt=\"Advanced Search\">";
$searchImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smSearch.gif\" title=\"Search {$searchTitle}\" alt=\"Search\">";
$searchSpecLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}searchSpecLrg.gif\" title=\"Click here for Specification Search\" alt=\"Specification Search\">";
$securityInqImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}imgKey.gif\" title=\"Click here to view Security Inquiry\" alt=\"Security\">";
$selectAcceptImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqAccept.gif\" title=\"Click here to accept selection\" alt=\"Accept\">";
$selectAllImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqAcceptAll.gif\" title=\"Click here to select all\" alt=\"Select All\">";
$selectBackImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqLeft.gif\" title=\"Previous page\" alt=\"Back\">";
$selectCancelImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqNoChange.gif\" title=\"Click here to cancel selection\" alt=\"Cancel\">";
$selectClearImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqClear.gif\" title=\"Click here to clear selections\" alt=\"Clear\">";
$selectContinueImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqContinue.gif\" title=\"Click here to continue\" alt=\"Continue\">";
$selectCriteriaImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqInfo.gif\" title=\"Selection Criteria\" alt=\"Selection Criteria\">";
$selectedImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}selected.gif\" title=\"Selected\" alt=\"Selected\">";
$selectedImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}selected.gif\" title=\"Selected\" alt=\"Selected\">";
$selectedOptionImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smCheck.gif\" title=\"Option Selected\" alt=\"Option Selected\">";
$selectImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smExpand.gif\" title=\"Click to view more detail\" alt=\"Expand\">";
$selectImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgInsertIntoForm.gif\" title=\"Click here to select this record\" alt=\"Select\">";
$selectImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smUpdate.gif\" title=\"Select to process\" alt=\"Select\">";
$selectResetImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqRefresh.gif\" title=\"Click here to reset selections\" alt=\"Reset\">";
$selectSaveImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqFolder.gif\" title=\"Click here to save record\" alt=\"Save\">";
$selectUpdateImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqAdd.gif\" title=\"Click here to update selection\" alt=\"Update\">";
$setReadyToApproveAllImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqAcceptAll.gif\" title=\"Set Requisition Ready For Approval\" alt=\"Set Ready\">";
$shipWithInvoice= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqUpdate.gif\" title=\"Accept shipment and print invoice\" alt=\"Ship/Invoice\">";
$shipWithInvoive= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqUpdate.gif\" title=\"Accept shipment and print invoice\" alt=\"Ship/Invoice\">";
$signOnImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}go.gif\" title=\"Click here to continue\" alt=\"Go\">";
$singleLvlWUImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}singleLevelWhereUsed.gif\" title=\"View the single level where used\" alt=\"Single Level Where Used\">";
$smC= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smC.gif\" title=\"{$smCTitle}\" alt=\"C\">";
$smF= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smF.gif\" title=\"{$smFTitle}\" alt=\"F\">";
$smH= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smH.gif\" title=\"{$smHTitle}\" alt=\"H\">";
$smMoreInfoImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}moreInfo.gif\" title=\"Click here for more information\" alt=\"More\">";
$smNoPay= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smNoPay.gif\" title=\"Deactivate Employee Payroll\" alt=\"NoPay\">";
$smO= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smO.gif\" title=\"{$smOTitle}\" alt=\"O\">";
$smS= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smS.gif\" title=\"{$smSTitle}\" alt=\"S\">";
$smU= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smU.gif\" title=\"{$smUTitle}\" alt=\"U\">";
$sortAscPrimary= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smPointBlackDownSolid.gif\" title=\"Ascending sequence\" alt=\"A\">";
$sortAscSecondary= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smPointBlackDown.gif\" title=\"Ascending sequence\" alt=\"A\">";
$sortDscPrimary= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smPointBlackUpSolid.gif\" title=\"Descending sequence\" alt=\"D\">";
$sortDscSecondary= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smPointBlackUp.gif\" title=\"Descending sequence\" alt=\"D\">";
$sourceSelectionImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqAdd.gif\" title=\"Click here to add or remove source members\" alt=\"Select Source Members\">";
$sourceViewImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqInfo.gif\" title=\"View Source Members Selected\" alt=\"View Source Members\">";
$specSheetImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgForm.gif\" title=\"Click here to create a spec sheet\" alt=\"Spec Sheet\">";
$specSheetMed= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqForm.gif\" title=\"Click here to create a spec sheet\" alt=\"Spec Sheet\">";
$substituteSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smS.gif\" title=\"Substitute Item\" alt=\"S\">";
$supervisorApproval= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}approved.gif\" title=\"Supervisor Approval\" alt=\"Supervisor Approval\">";
$tableColumn= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smC.gif\" title=\"Click here to maintain the table columns\" alt=\"C\">";
$tableLink= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smL.gif\" title=\"Click here to display a list of table links\" alt=\"Link\">";
$tableLinkParm= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smP.gif\" title=\"Click here to maintain table link parameters\" alt=\"Parms\">";
$termImageLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}terminateLarge.gif\" title=\"Terminate\" alt=\"Terminate\">";
$termImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}terminateSmall.gif\" title=\"Terminate\" alt=\"Terminate\">";
$topOfFormImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqUp.gif\" title=\"Top Of Form\" alt=\"Top\">";
$transferToProductionImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}selected.gif\" title=\"Transfer To Production\" alt=\"Transfer\">";
$transferToQAImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}selected.gif\" title=\"Transfer To Q/A\" alt=\"Transfer\">";
$unauthorizedImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smCloseLine.gif\" title=\"{$unauthorizedTitle}\" alt=\"Unauthorized\">";
$usageExistsSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smUsageExists.gif\" title=\"Click here to display account usage\" alt=\"Usage\">";
$usageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smUsage.gif\" title=\"Click here to add account usage\" alt=\"Add Usage\">";
$wfActive= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}wfactive.gif\" title=\"Click here to view workflow history\" alt=\"Workflow\">";
$wfActivityImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}wfActivity.gif\" title=\"Display list of Activities\" alt=\"View Activities\">";
$wfAddDelgImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}wfParticipant.gif\" title=\"Add To Delegated Participant\" alt=\"Add Delegated Participant\">";
$wfApprImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}approved.gif\" title=\"Click here to go to approval for the Work Item in [{$V_ATD2W}]\" alt=\"Approve\">";
$wfAttachWIDetail= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smAttachment.gif\" title=\"Click here to view attachments for Detail Point\" alt=\"Detail Point Attachments\">";
$wfAttachWIPoint= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smAttachment.gif\" title=\"Click here to view attachments for Point\" alt=\"Point Attachments\">";
$wfCancelImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgCancel.gif\" title=\"Click here to cancel the review\" alt=\"Cancel\">";
$wfChgWorkItemSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smUpdate.gif\" title=\"Change Work Item Expiration or Priority\" alt=\"Update\">";
$wfCommentImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smComment.gif\" title=\"Display comments\" alt=\"Comment\">";
$wfConditionImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}wfCondition.gif\" title=\"Display conditions\" alt=\"Condition\">";
$wfDataImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}glasses.gif\" title=\"Display Application Data\" alt=\"Application Data\">";
$wfDelegateImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}wfParticipant.gif\" title=\"Click here to revoke the Delegation\" alt=\"Revoke Delegation\">";
$wfFailImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}rejected.gif\" title=\"Click here to reject the Work Item\" alt=\"Fail\">";
$wfFailImageOpt= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}rejected.gif\" title=\"Click here to reject the Work Item and select Transition\" alt=\"Fail\">";
$wfInstructionImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}moreinfo.gif\" title=\"Click here to reject the Work Item\" alt=\"Fail\">";
$wfMarkReview= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smUpdate.gif\" title=\"Mark As Reviewed\" alt=\"Mark\">";
$wfNotificationImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}phone.gif\" title=\"Display notifications\" alt=\"Notification\">";
$wfParameterImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}wfParameter.gif\" title=\"Display parameters\" alt=\"Parameter\">";
$wfParticipantDlg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}wfParticipant.gif\" title=\"Delegate participant\" alt=\"Participant\">";
$wfParticipantImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}wfParticipant.gif\" title=\"Display participants\" alt=\"Participant\">";
$wfPassImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}approved.gif\" title=\"Click here to accept with Current Values\" alt=\"Pass\">";
$wfPassImageOpt= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}approved.gif\" title=\"Click here to accept with Current Values and select Transition\" alt=\"Pass\">";
$wfPassUndoImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}approved.gif\" title=\"Click here to accept without Current Values\" alt=\"Pass with Undo\">";
$wfPassUndoImageOpt= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}approved.gif\" title=\"Click here to accept without Current Values and select Transition\" alt=\"Pass with Undo\">";
$wfTransitionImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}wfActivity.gif\" title=\"Display transitions\" alt=\"Transition\">";
$wfTreeBlank= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smTreeBlank.gif\">";
$wfTreeMinus= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smTreeMinus.gif\" title=\"Collapse Row\" alt=\"Collapse\">";
$wfTreePlus= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smTreePlus.gif\" title=\"Explode Row\" alt=\"Explode\">";
$wfTreeSub= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smTreeSub.gif\">";
$wfTreeVLine= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smTreeVLine.gif\">";
$wfValidationImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smX.gif\" title=\"Display validations\" alt=\"Validation\">";
$whereusedImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smSearch.gif\" title=\"Where Used\">";
$whsImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smWarehouse.gif\" title=\"Display Warehouse Records\" alt=\"Warehouse\">";
$whsSupply= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smS.gif\" title=\"Update Warehouse Supply\" alt=\"S\">";
$wildChgImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqBinoculars.gif\" title=\"Click here to change the current search criteria\" alt=\"Change search\">";
$wildClearImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqStop.gif\" title=\"Click here to clear the current search criteria\" alt=\"Clear search\">";
$wildClearLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqStop.gif\" title=\"Click here to clear the current search criteria\" alt=\"Clear search\">";
$wildDftImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqGetSettings.gif\" title=\"Click here to use the default search criteria\" alt=\"Open default search\">";
$wildDftLrg= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqGetSettings.gif\" title=\"Click here to retrieve the default search criteria\" alt=\"Open default search\">";
$wildSetImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqSaveSettings.gif\" title=\"Click here to save the current search criteria as the default\" alt=\"Save current as default\">";
$wildSortImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqSort.gif\" title=\"Click here sort on multiple columns\" alt=\"Sort\">";
$wildView= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqI.gif\" title=\"{$wildViewTitle}\" alt=\"View current search\">";
$wildViewImage= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgSqQuestion.gif\" title=\"Click here to view the current search criteria\" alt=\"View current search\">";
$workflowBatchImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}approved.gif\" title=\"Send Batch to History\" alt=\"Batch to History\">";
$workflowImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}approved.gif\" title=\"Send Interface to Workflow\" alt=\"Workflow\">";
$xMLFormatDesc= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}lgXML.gif\" title=\"Click here for XML Export\" alt=\"XML Export\">";
$xmlImport= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}smXML.gif\" title=\"Click here to Import XML\" alt=\"XML\">";
$xmlTransformImageSml= (string) "<img border=\"0\" src=\"{$homeURL}{$imagePath}approved.gif\" title=\"Transform XML\" alt=\"Transform XML\">";
?>
