-- sg_fix5 backup -- 2026-06-13 23:09:35
-- UNDO: DELETE FROM S5HDSDATA.SYPORR WHERE TRIM(PRROLE) IN (rList) AND TRIM(PRPORT) NOT IN ('SGINQ','SGDASH','SGDINT','SGRPT','SGSOP') AND PRTSUS='BILL' AND PRTSTP >= '2026-06-13';

-- COLLECTION: 0 non-SG rows (AFFECTED -- will get rows added)
-- ENAPOLES: 0 non-SG rows (AFFECTED -- will get rows added)
-- HD_ALL: 0 non-SG rows (AFFECTED -- will get rows added)
-- HD_ALL_SG: 0 non-SG rows (AFFECTED -- will get rows added)
-- PRODMANAGR: 0 non-SG rows (AFFECTED -- will get rows added)
-- PRODUCTION: 0 non-SG rows (AFFECTED -- will get rows added)
-- TIFFANY: 0 non-SG rows (AFFECTED -- will get rows added)
-- WIDGETS: 0 non-SG rows (AFFECTED -- will get rows added)
-- HD_SLSM: 0 non-SG rows (AFFECTED -- will get rows added)
