-- SG Fix v8 Backup -- 2026-06-13 18:31:21
-- Restore SYPORT FPRESV and SYURLM FUURL/FUDESCU/FUTSUS/FUTSWS for SG portals

-- SYPORT restore
UPDATE SYPORT SET FPRESV = 'Y' WHERE FPPORT = 'SGDASH' AND TRIM(FPPAGE) = '';
UPDATE SYPORT SET FPRESV = 'Y' WHERE FPPORT = 'SGDINT' AND TRIM(FPPAGE) = '';
UPDATE SYPORT SET FPRESV = 'Y' WHERE FPPORT = 'SGINQ' AND TRIM(FPPAGE) = '';
UPDATE SYPORT SET FPRESV = 'Y' WHERE FPPORT = 'SGRPT' AND TRIM(FPPAGE) = '';
UPDATE SYPORT SET FPRESV = 'Y' WHERE FPPORT = 'SGSOP' AND TRIM(FPPAGE) = '';

-- SYURLM restore
UPDATE SYURLM SET FUURL = '', FUDESCU = '', FUTSUS = '', FUTSWS = '' WHERE FUID = 'SGDASH/PORTAL';
UPDATE SYURLM SET FUURL = '', FUDESCU = '', FUTSUS = '', FUTSWS = '' WHERE FUID = 'SGDINT/PORTAL';
UPDATE SYURLM SET FUURL = '', FUDESCU = '', FUTSUS = '', FUTSWS = '' WHERE FUID = 'SGINQ/PORTAL';
UPDATE SYURLM SET FUURL = '', FUDESCU = '', FUTSUS = '', FUTSWS = '' WHERE FUID = 'SGRPT/PORTAL';
UPDATE SYURLM SET FUURL = '', FUDESCU = '', FUTSUS = '', FUTSWS = '' WHERE FUID = 'SGSOP/PORTAL';