-- SG full menu backup -- 2026-06-13 21:13:17
-- UNDO: DELETE FROM S5HDSDATA.SYPORT WHERE FPPORT IN ('SGINQ','SGDASH','SGDINT','SGRPT','SGSOP') AND TRIM(FPPAGE)<>'';
-- UNDO: DELETE FROM S5HDSDATA.SYPORR WHERE TRIM(PRROLE) IN ('ACCOUNTING','ACCOUNTMAN','COLLECTION','CUSTSRVC','CUSTSRVMGR','EBORRELL','ENAPOLES','HD_ALL','HD_ALL_SG','INVENTORY','LARIANN','MCRESPO','MFGVP','PLANNING','PLANPRDPUR','PRODMANAGR','PRODUCTION','PURCHASING','SALES','SALESADMIN','TIFFANY','WIDGETS','HD_SLSM') AND PRPORT IN ('SGINQ','SGDASH','SGDINT','SGRPT','SGSOP');


-- SYPORT
INSERT INTO SYPORT (FPPORT,FPPAGE,FPSEQ,FPID,FPDESC,FPTITL,FPRESV,FPDESCU,FPTSTP,FPTSUS,FPTSWS,FPTSPT) VALUES ('SGDASH','','1.00','SGDASH/PORTAL','','SG Dashboards','','','2026-06-10-17.21.16.422682','BILL','DSP01','Y');
INSERT INTO SYPORT (FPPORT,FPPAGE,FPSEQ,FPID,FPDESC,FPTITL,FPRESV,FPDESCU,FPTSTP,FPTSUS,FPTSWS,FPTSPT) VALUES ('SGDINT','','1.00','SGDINT/PORTAL','','SG Data Integrity','','','2026-06-10-17.21.16.479867','BILL','DSP01','Y');
INSERT INTO SYPORT (FPPORT,FPPAGE,FPSEQ,FPID,FPDESC,FPTITL,FPRESV,FPDESCU,FPTSTP,FPTSUS,FPTSWS,FPTSPT) VALUES ('SGINQ','','1.00','SGINQ/PORTAL','','SG Inquiries','','','2026-06-10-17.21.16.334872','BILL','DSP01','Y');
INSERT INTO SYPORT (FPPORT,FPPAGE,FPSEQ,FPID,FPDESC,FPTITL,FPRESV,FPDESCU,FPTSTP,FPTSUS,FPTSWS,FPTSPT) VALUES ('SGRPT','','1.00','SGRPT/PORTAL','','SG Reports','','','2026-06-10-17.21.16.535429','BILL','DSP01','Y');
INSERT INTO SYPORT (FPPORT,FPPAGE,FPSEQ,FPID,FPDESC,FPTITL,FPRESV,FPDESCU,FPTSTP,FPTSUS,FPTSWS,FPTSPT) VALUES ('SGSOP','','1.00','SGSOP/PORTAL','','SG SOP''s','','','2026-06-10-17.21.16.590915','BILL','DSP01','Y');

-- SYPORR