-- SYPORR Backup -- 2026-06-13 20:40:39
-- Existing SYPORR rows for 23 roles x SG portals (before insert)
-- Undo command: DELETE FROM SYPORR WHERE PRROLE IN ('ACCOUNTING','ACCOUNTMAN','COLLECTION','CUSTSRVC','CUSTSRVMGR','EBORRELL','ENAPOLES','HD_ALL','HD_ALL_SG','INVENTORY','LARIANN','MCRESPO','MFGVP','PLANNING','PLANPRDPUR','PRODMANAGR','PRODUCTION','PURCHASING','SALES','SALESADMIN','TIFFANY','WIDGETS','HD_SLSM') AND PRPORT IN ('SGINQ','SGDASH','SGDINT','SGRPT','SGSOP');

-- No existing rows found (INSERT is safe, undo with DELETE above)