<?php
// FixMenuTargets.php
// TARGET SCHEMA: SGHDSDATA (EIP Live only)
//
// Fixes FUTRGT='_blank' on the 31 specific SG portal sub-menu entries
// created by SgApplyAll.php (30 rows) and InsertMgmtPortal (1 row).
// Uses an EXPLICIT IN list — does NOT touch any other SYURLM rows.
//
// Deliberately excluded (intentional _blank or no submenus):
//   SGPRICINGINQUIRY  — opens new window by design, never touch
//   SG_DOCUMENTATION  — no submenus, already correct
//   Any other SG* entry not in the list below
//
// Preview: https://portal.screen-graphics.com:5601/Custom/SG/FixMenuTargets.php
// Execute: https://portal.screen-graphics.com:5601/Custom/SG/FixMenuTargets.php?confirm=FIX

$confirm = (isset($_GET['confirm']) && $_GET['confirm'] === 'FIX');

// Exactly the FUIDs generated by SgApplyAll.php Step 2 (5 portals x 6 cats = 30)
// plus SGMGMT_OE from InsertMgmtPortal — nothing else.
$targetFuids = array(
    'SGINQ_ACCT',    'SGINQ_INVMGMT',  'SGINQ_MFG',    'SGINQ_OE',    'SGINQ_PLN',    'SGINQ_PUR',
    'SGDASH_ACCT',   'SGDASH_INVMGMT', 'SGDASH_MFG',   'SGDASH_OE',   'SGDASH_PLN',   'SGDASH_PUR',
    'SGDINT_ACCT',   'SGDINT_INVMGMT', 'SGDINT_MFG',   'SGDINT_OE',   'SGDINT_PLN',   'SGDINT_PUR',
    'SGRPT_ACCT',    'SGRPT_INVMGMT',  'SGRPT_MFG',    'SGRPT_OE',    'SGRPT_PLN',    'SGRPT_PUR',
    'SGSOP_ACCT',    'SGSOP_INVMGMT',  'SGSOP_MFG',    'SGSOP_OE',    'SGSOP_PLN',    'SGSOP_PUR',
    'SGMGMT_OE',
);

$inList = "'" . implode("','", $targetFuids) . "'";

$conn = db2_connect('*LOCAL', '', '');
if (!$conn) die('DB error: ' . htmlspecialchars(db2_conn_errormsg()));

$previewSql = "SELECT FUID, FUTRGT, FUTITL FROM SGHDSDATA.SYURLM
               WHERE FUID IN ($inList) AND RTRIM(FUTRGT) = '_blank'
               ORDER BY FUID";

$updateSql  = "UPDATE SGHDSDATA.SYURLM SET FUTRGT = ''
               WHERE FUID IN ($inList) AND RTRIM(FUTRGT) = '_blank'";

$rows = array();
$s = @db2_exec($conn, $previewSql);
if ($s) { while ($r = db2_fetch_assoc($s)) $rows[] = $r; }

$updateResult = null;
$rowsAffected = 0;
if ($confirm && !empty($rows)) {
    $updateResult = @db2_exec($conn, $updateSql);
    if ($updateResult !== false) {
        $rowsAffected = db2_num_rows($updateResult);
    }
}

db2_close($conn);
?>
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Fix Menu Targets</title>
<style>
* { box-sizing:border-box; margin:0; padding:0; }
body { font:13px Arial,sans-serif; background:#f0f2f5; padding:20px; }
.hdr { background:linear-gradient(135deg,#2a5a8c,#1a3d5c); color:#fff;
       padding:12px 20px; border-radius:5px; border-bottom:3px solid #f90;
       margin-bottom:16px; font-size:17px; font-weight:bold; }
.hdr .sub { font-size:11px; opacity:.75; margin-top:3px; font-weight:normal; }
.ok   { background:#e8f5e9; border:1px solid #a5d6a7; border-radius:5px; padding:12px 16px; margin-bottom:14px; }
.warn { background:#fff8e1; border:1px solid #ffe082; border-radius:5px; padding:12px 16px; margin-bottom:14px; }
.excl { background:#f3e5f5; border:1px solid #ce93d8; border-radius:5px; padding:10px 16px; margin-bottom:14px; font-size:12px; }
table { border-collapse:collapse; width:100%; background:#fff; border-radius:4px; overflow:hidden;
        box-shadow:0 1px 4px rgba(0,0,0,.08); margin-bottom:14px; }
th { background:#2a5a8c; color:#fff !important; font-weight:bold !important; padding:5px 10px; text-align:left; font-size:11px; }
td { padding:4px 10px; font-size:12px; font-family:monospace; border-bottom:1px solid #f0f0f0; }
.btn { display:inline-block; margin-top:10px; background:#c62828; color:#fff;
       font-weight:bold; padding:10px 28px; border-radius:4px;
       text-decoration:none; font-size:14px; }
.btn:hover { background:#b71c1c; }
</style>
</head>
<body>
<div class="hdr">
  Fix Menu Targets &mdash; SGHDSDATA (EIP Live)
  <div class="sub">Sets FUTRGT='' on 31 specific SG portal sub-menu rows only &nbsp;|&nbsp; <?php echo date('Y-m-d H:i:s'); ?></div>
</div>

<div class="excl">
  <strong>Explicitly excluded (will never be touched by this script):</strong>
  SGPRICINGINQUIRY (intentional _blank), SG_DOCUMENTATION (no submenus, already correct),
  and any other SYURLM row not in the 31-item target list.
</div>

<?php if ($confirm): ?>
  <?php if ($updateResult === false): ?>
    <div class="warn"><strong>UPDATE failed.</strong> <?php echo htmlspecialchars(db2_stmt_errormsg()); ?></div>
  <?php elseif ($rowsAffected > 0): ?>
    <div class="ok"><strong>Done.</strong> <?php echo $rowsAffected; ?> row(s) updated. EIP submenu items will now open in the same window. Log out and back in to verify.</div>
  <?php else: ?>
    <div class="ok"><strong>Nothing to do.</strong> No target rows have FUTRGT='_blank' &mdash; already fixed or never set.</div>
  <?php endif; ?>
<?php else: ?>
  <?php if (empty($rows)): ?>
    <div class="ok"><strong>Nothing to fix.</strong> None of the 31 target FUIDs in SGHDSDATA.SYURLM have FUTRGT='_blank'. No changes needed.</div>
  <?php else: ?>
    <div class="warn">
      <strong><?php echo count($rows); ?> of the 31 target row(s) have FUTRGT='_blank' and will be updated.</strong><br>
      This makes these EIP submenu flyout items open in the same window instead of a new window.
      SGPRICINGINQUIRY and all other non-listed entries are untouched.
    </div>
    <table>
      <tr><th>FUID</th><th>Current FUTRGT</th><th>Title</th></tr>
      <?php foreach ($rows as $r): ?>
      <tr>
        <td><?php echo htmlspecialchars($r['FUID']); ?></td>
        <td style="color:#c62828"><?php echo htmlspecialchars($r['FUTRGT']); ?></td>
        <td><?php echo htmlspecialchars($r['FUTITL']); ?></td>
      </tr>
      <?php endforeach; ?>
    </table>
    <a class="btn" href="?confirm=FIX">Fix <?php echo count($rows); ?> Row(s) &mdash; SGHDSDATA Live</a>
    <p style="margin-top:8px;font-size:11px;color:#666;">Only touches SGHDSDATA (EIP Live). SG5 test (S5HDSDATA) is not affected.</p>
  <?php endif; ?>
<?php endif; ?>

</body>
</html>
