<?php
$ARApplCashStyleSheet= (string) "HDSARApplCash.css";
$banner= (string) "HDSbanner.php";
$baseTable= (string) "class=\"basetable\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" summary=\"basetable\"";
$blank= (string) "blank.php";
$bodyTagAttr= (string) "";
$calStyleSheet= (string) "HDSCalendar.css";
$casStyleSheet= (string) "HDSGeneral.css";
$cmtBanner= (string) "blank.php";
$cmthrTagAttr= (string) "<hr>";
$cmtStyleSheet= (string) "HDSGeneral.css";
$cmtTrailer= (string) "blank.php";
$companyLogo= (string) "yourLogoName.xxx";
$contentTable= (string) "class=\"contenttable\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" summary=\"contenttable\"";
$displayMenuImages= (string) "N";
$docType= (string) "doctype.php";
$dspMaxRowsDft= (string) "50";
$fldTextErrOvr= (string) "style=color:red";
$fmtBanner= (string) "HDSBannerFmt.php";
$fmthrTagAttr= (string) "<hr>";
$fmtStyleSheet= (string) "HDSGeneral.css";
$fmtTrailer= (string) "HDSTrailerFmt.php";
$genericHead= (string) "HDSGenHeading.php";
$GLDDStyleSheet= (string) "HDSGLDrillDown.css";
$headInclude= (string) "head.php";
$helpCursor= (string) "onmouseover=\"this.style.cursor='help';\"";
$hrTagAttr= (string) "<hr>";
$imageBanner= (string) "blank.php";
$imageBorder= (string) "0";
$imagehrTagAttr= (string) "<hr>";
$imageTrailer= (string) "blank.php";
$inquiryBanner= (string) "blank.php";
$inquiryhrTagAttr= (string) "<hr>";
$inquiryTrailer= (string) "blank.php";
$menuStyleSheet= (string) "HDSMenu.css";
$menuTable= (string) "class=\"menutable\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" summary=\"menutable\"";
$mobileStyleSheet= (string) "HDSMobile.css";
$popBanner= (string) "blank.php";
$popTrailer= (string) "blank.php";
$popupCalTable= (string) "class=\"popupcaltable\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" summary=\"popupcaltable\"";
$prtMaxRowsDft= (string) "99999";
$qlinkStyleSheet= (string) "HDSQuickLink.css";
$quicklinkDspImage= (string) "N";
$quickLinkTable= (string) "class=\"quicklinktable\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" summary=\"quicklinktable\"";
$quickSearchTable= (string) "class=\"quicksearchtable\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" summary=\"quicksearchtable\"";
$searchBanner= (string) "blank.php";
$searchhrTagAttr= (string) "<hr>";
$searchTrailer= (string) "blank.php";
$tabStyleSheet= (string) "HDSTabs.css";
$touchStyleSheet= (string) "HDSTouchScreen.css";
$trailer= (string) "HDSTrailer.php";
?>
