<?php
$accountsByProdClass= (string) "N";
$allowMixedCasePasswords= (string) "Y";
$altBaseVar= (string) "BaseConfigurationT1.icl";
$anonymousUser= (string) "EIPDEFAULT";
$anonymousWelcomePage= (string) "AnonymousWelcome.php";
$AppsInHd= (string) "";
$AppsInHdERP= (string) "";
$AvaTaxCompany= (string) "";
$AvaTaxDefaultCompany= (string) "Screen Graphics LLC";
$AvaTaxFreight= (string) "FR";
$AvaTaxSpecialChg= (string) "O0000000";
$baseExportFile= (string) "BaseExport.php";
$cGIPath= (string) "/harris-CGI/";
$convertEEOEthnicCategory= (string) "";
$convertEEOJobCategory= (string) "";
$creditcardURL= (string) "http://portal.screen-graphics.com:10080";
$curbstoneCustomerNumber= (string) "00321";
$dataBaseID= (string) "S5";
$libraryList= array("S5HDSDATA","SG5MODPGM","SG5STDPGM","AVATAXR2","SGPGM","SG","QTEMP","DRVSFLEX","QGPL","INFOPRINT","HSSF","RPGMAIL","PROITRG","C3","SEQUEL","ROBOTLIB","ZENDSVR6","CGIDEV2");
$chgLibraryList= (string) "CHGLIBL LIBL( S5HDSDATA SG5MODPGM SG5STDPGM AVATAXR2 SGPGM SG QTEMP DRVSFLEX QGPL INFOPRINT HSSF RPGMAIL PROITRG C3 SEQUEL ROBOTLIB ZENDSVR6 CGIDEV2)";
$description= (string) "Screen Graphics Information Portal";
$distinctSQL= (string) "";
$fileSQL= (string) "";
$HDphpPath= (string) "";
$HDToolkitPath= (string) "";
$helpPath= (string) "/HarrisData/EIP/help/";
$homePath= (string) "/HarrisData/EIP/";
$homeURL= (string) "https://portal.screen-graphics.com:5610";
$httpPort= (string) "";
$imagePath= (string) "/HarrisData/EIP/icon/";
$pgmLibrary= (string) "HDSSTDPGM";
$phpPath= (string) "/";
$selectSQL= (string) "";
$signonURL= (string) "https://portal.screen-graphics.com:5610/eip";
$sql_Record_Count= (string) "";
$sysDateFormat= (string) "MDY";
$title= (string) "T1 - TEST EIP";
$uploadDirectory= (string) "Attachments/";
$uv_Sql= (string) "";
$webRegCurFile= (string) "ACTIVE";
$webRegLibrary= (string) "WEBREG";
$webRegPath= (string) "/qsys.lib/WEBREG.lib/";
$xmlPath= (string) "/NetData/XML/";
require_once 'BaseFormat.php';
require_once 'BaseIcons.php';
require_once 'BaseThemesSG.php';
?>
