<?php
$acceptOrderMsg= (string) "Click OK to complete your order";
$allowInquiryOnly= (string) "N";
$allowItemSearch= (string) "Y";
$allowPriceInq= (string) "Y";
$autoCloseItemWin= (string) "N";
$cartEmptyMsg= (string) "Your shopping cart is empty.";
$catBanner= (string) "{$banner}";
$catChildImgSize= (string) "height=\"100\" width=\"100\"";
$catChildPerRow= (string) "1";
$catDspHeadings= (string) "Y";
$categoryImgSize= (string) "height=\"70\"  width=\"70\"";
$cathrTagAttr= (string) "<hr size=\"4\" width=\"95%\" align=\"left\" noshade>";
$catIndentChar= (string) "&nbsp;";
$catItemImgLarge= (string) "height=\"250\" width=\"250\"";
$catItemImgSmall= (string) "height=\"30\"  width=\"30\"";
$catItemsPerRow= (string) "1";
$catNbrOfRows= (string) "8";
$catParentImgSize= (string) "";
$catParentPerRow= (string) "1";
$catSeqItemDesc= (string) "03";
$catSeqItemImage= (string) "01";
$catSeqItemNbr= (string) "02";
$catSeqOrderQty= (string) "05";
$catSeqPrice= (string) "04";
$catSeqQtyAvail= (string) "";
$catSeqUDA1= (string) "";
$catSeqUDA2= (string) "";
$catSeqUDA3= (string) "";
$catSeqUDA4= (string) "";
$catSeqUDA5= (string) "";
$catSeqUDN1= (string) "";
$catSeqUDN2= (string) "";
$catSeqUDN3= (string) "";
$catSeqUDN4= (string) "";
$catSeqUDN5= (string) "";
$catSeqUXA1= (string) "";
$catSeqUXA2= (string) "";
$catSeqUXA3= (string) "";
$catSeqUXA4= (string) "";
$catSeqUXA5= (string) "";
$catSeqUXD1= (string) "";
$catSeqUXD2= (string) "";
$catSeqUXD3= (string) "";
$catSeqUXD4= (string) "";
$catSeqUXD5= (string) "";
$catSeqUXN1= (string) "";
$catSeqUXN2= (string) "";
$catSeqUXN3= (string) "";
$catSeqUXN4= (string) "";
$catSeqUXN5= (string) "";
$catStyleSheet= (string) "HDSGeneral.css";
$catTrailer= (string) "{$blank}";
$catTypQtyAvail= (string) "Q";
$creditCardReq= (string) "N";
$creditCardTerms= (string) "CC";
$defaultOrderType= (string) "W";
$dspChildDesc= (string) "N";
$dspHdrCat= (string) "Y";
$dspMenuOptions= (string) "Y";
$dspParentDesc= (string) "N";
$orderConfMsg= (string) "Thank you for your order.  Your order confirmation number is {$orderNumber}";
$refNbrDesc= (string) "Reference Number";
$refNbrReq= (string) "N";
$viewCartImgSize= (string) "height=\"30\"  width=\"30\"";
require_once 'BaseCatalogIcons.php';
?>
