<?php
$userViewVar = (string) "";
Concat_UserView("@@nosu",$uv_UserNotSetUp);
Concat_UserView("@@co#@",$uv_CompanyName);
Concat_UserView("@@fac#",$uv_FacilityName);
Concat_UserView("@@tin#",$uv_PayerTINName);
Concat_UserView("@@bnk#",$uv_BankName);
Concat_UserView("@@acct",$uv_AccountName);
Concat_UserView("@@sub@",$uv_SubaccountName);
Concat_UserView("@@buyr",$uv_BuyerName);
Concat_UserView("@@vtyp",$uv_VendorTypeName);
Concat_UserView("@@vend",$uv_VendorName);
Concat_UserView("@@slsm",$uv_SalesmanName);
Concat_UserView("@@ccls",$uv_CustomerClassName);
Concat_UserView("@@crgn",$uv_RegionName);
Concat_UserView("@@bllc",$uv_BillingLocationName);
Concat_UserView("@@cust",$uv_CustomerName);
Concat_UserView("@@payr",$uv_PayerName);
Concat_UserView("@@fein",$uv_FederalEINName);
Concat_UserView("@@peco",$uv_HRCompanyName);
Concat_UserView("@@pelc",$uv_HRLocationName);
Concat_UserView("@@bank",$uv_PRBankName);
Concat_UserView("@@dept",$uv_HomeDepartmentName);
Concat_UserView("@@payt",$uv_PayTypeName);
Concat_UserView("@@payd",$uv_SalaryControlName);
Concat_UserView("@@prem",$uv_PREmployeeName);
Concat_UserView("@@peem",$uv_HREmployeeName);
Concat_UserView("@@schd",$uv_ScheduleName);
Concat_UserView("@@grp@",$uv_GroupName);
Concat_UserView("@@code",$uv_DataCollectionName);
Concat_UserView("@@lcod",$uv_LaborCodeName);
Concat_UserView("@@incd",$uv_IndirectDowntimeName);
Concat_UserView("@@plt@",$uv_PlantName);
Concat_UserView("@@mfdp",$uv_MfgDepartmentName);
Concat_UserView("@@wc@@",$uv_WorkCenterName);
Concat_UserView("@@itc@",$uv_PltInventoryTypeName);
Concat_UserView("@@ptyp",$uv_PltPartTypeName);
Concat_UserView("@@pgrp",$uv_ProductGroupName);
Concat_UserView("@@clas",$uv_PartClassName);
Concat_UserView("@@pcls",$uv_ProductClassName);
Concat_UserView("@@whs@",$uv_WarehouseName);
Concat_UserView("@@pitc",$uv_ProdInventoryTypeName);
Concat_UserView("@@ppty",$uv_ProdPartTypeName);
Concat_UserView("@@cycl",$uv_CountGroupName);
Concat_UserView("@@stkr",$uv_StockroomName);
Concat_UserView("@@aile",$uv_AileName);
Concat_UserView("@@sloc",$uv_StockLocationName);
Concat_UserView("@@oocd",$uv_OEOrderTypeName);
Concat_UserView("@@pocd",$uv_POOrderTypeName);
Concat_UserView("@@ttyp",$uv_TransactionTypeName);
Concat_UserView("@@site",$uv_SiteName);
Concat_UserView("@@prop",$uv_PropertyTypeName);
Concat_UserView("@@fmcd",$uv_FamilyCodeName);
$userViewVar .=  "}{";

$uv_Sql = (string) "";
$returnValue=User_View($profileHandle, $dataBaseID, $userViewVar, $uv_Sql);
$uv_Sql = $returnValue['uv_Sql'];
$userViewVar = $returnValue['userViewVar'];
	
$uv_UserNotSetUp =  (string)"";
$uv_CompanyName =  (string)"";
$uv_FacilityName =  (string)"";
$uv_PayerTINName =  (string)"";
$uv_BankName =  (string)"";
$uv_AccountName =  (string)"";
$uv_SubaccountName =  (string)"";
$uv_BuyerName =  (string)"";
$uv_VendorTypeName =  (string)"";
$uv_VendorName =  (string)"";
$uv_SalesmanName =  (string)"";
$uv_CustomerClassName =  (string)"";
$uv_RegionName = (string)" ";
$uv_BillingLocationName = (string)" ";
$uv_CustomerName = (string)" ";
$uv_PayerName = (string)" ";
$uv_FederalEINName = (string)" ";
$uv_HRCompanyName = (string)" ";
$uv_HRLocationName = (string)" ";
$uv_PRBankName = (string)" ";
$uv_HomeDepartmentName = (string)" ";
$uv_PayTypeName = (string)" ";
$uv_SalaryControlName = (string)" ";
$uv_PREmployeeName = (string)" ";
$uv_HREmployeeName = (string)" ";
$uv_ScheduleName = (string)" ";
$uv_GroupName = (string)" ";
$uv_DataCollectionName = (string)" ";
$uv_LaborCodeName = (string)" ";
$uv_IndirectDowntimeName = (string)" ";
$uv_PlantName = (string)" ";
$uv_MfgDepartmentName = (string)" ";
$uv_WorkCenterName = (string)" ";
$uv_PltInventoryTypeName = (string)" ";
$uv_PltPartTypeName = (string)" ";
$uv_ProductGroupName = (string)" ";
$uv_PartClassName = (string)" ";
$uv_ProductClassName = (string)" ";
$uv_WarehouseName = (string)" ";
$uv_ProdInventoryTypeName = (string)" ";
$uv_ProdPartTypeName = (string)" ";
$uv_CountGroupName = (string)" ";
$uv_StockroomName = (string)" ";
$uv_AileName = (string)" ";
$uv_StockLocationName = (string)" ";
$uv_OEOrderTypeName = (string)" ";
$uv_POOrderTypeName = (string)" ";
$uv_TransactionTypeName = (string)" ";
$uv_SiteName = (string)" ";
$uv_PropertyTypeName = (string)" ";
$uv_FamilyCodeName = (string)" ";
?>